import Head from 'next/head'

export default function Home() {

  return (
    <div>
        <Head>
          <title>Test</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="bg-primary min-h-screen flex flex-col justify-center items-center selection:bg-highlight1-1">

          a


        </div>
    </div>
  )
}
